### ISSUE TITLE
- 214: Stop character cannot be used in <source> of a rule.

### ISSUE THREAD

**Issue by ramprax** [ratreya/google-ime-scm#1]
SA_ITRANS.scm is giving the  following error message:

File Name: C:\ProgramData\Google\Google Input Tools/com.google.input_tools.t13n.ime.sanskrit\schemes\SA_ITRANS.scm

- 214: Stop character cannot be used in <source> of a rule.

_ is declared as a stop character. But in line 214 of SA_ITRANS.scm, _ is being used.

**Comment by ratreya** [comment]
Thanks for reporting! I removed the redundant mapping for Anudatta that used stop character.
